<?php
// $Id: feeds_ui.module,v 1.1 2009/09/16 17:58:12 alexb Exp $
/**
 * @file
 */

/**
 * Implementation of hook_menu().
 */
function feeds_ui_menu() {
  $items = array();
  $items['admin/content/feeds'] = array(
    'title' => 'Feeds',
    'page callback' => 'feeds_ui_content_overview',
    'access arguments' => array('use feeds'),
    'file' => 'feeds_ui.admin.inc',
  );
  $items['admin/content/feeds/%feeds'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_content_feed', 3),
    'access arguments' => array('use feeds'),
    'file' => 'feeds_ui.admin.inc',
  );
  $items['admin/build/feeds'] = array(
    'title' => 'Feeds',
    'page callback' => 'feeds_ui_build_overview',
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
  );
  $items['admin/build/feeds/create'] = array(
    'title' => t('Create preset'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_create_form'),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/feeds/edit/%feeds'] = array(
    'title callback' => 'feed_ui_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_edit_form', 4),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/build/feeds/edit/%feeds/edit'] = array(
    'title' => t('Configuration'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/build/feeds/edit/%feeds/map'] = array(
    'title' => t('Mapping'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_mapping_form', 4),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/build/feeds/edit/%feeds/advanced'] = array(
    'title' => t('Advanced'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_ui_build_advanced_form', 4),
    'access arguments' => array('administer feeds'),
    'file' => 'feeds_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  return $items;
}

/**
 * Title callback.
 */
function feed_ui_title($feed) {
  return t('Edit !feed', array('!feed' => $feed->getId()));
}