<?php
// $Id: feeds_test.module,v 1.1 2009/10/23 21:13:47 alexb Exp $

/**
 * @file
 * Test module for Feeds.
 */

/**
 * Implementation of hook_menu().
 */
function feeds_test_menu() {
  $items = array();
  $items['opml-test-feed'] = array(
    'page callback' => 'feeds_test_opml_feed',
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Render an OPML feed pointing to local feeds.
 */
function feeds_test_opml_feed() {
  $path = dirname($GLOBALS['_SERVER']['SCRIPT_FILENAME']) .'/'. drupal_get_path('module', 'feeds') .'/tests/feeds/';

  drupal_set_header('Content-Type: application/rss+xml; charset=utf-8');
  $output =
'<?xml version="1.0" encoding="utf-8"?>
<opml version="1.1">
<head>
    <title>Feeds test OPML</title>
    <dateCreated>Fri, 16 Oct 2009 02:53:17 GMT</dateCreated>
    <ownerName></ownerName>
</head>
<body>
  <outline text="Feeds test group" >
       <outline title="Development Seed - Technological Solutions for Progressive Organizations" text="" xmlUrl="'. $path .'developmentseed.rss2" type="rss" />
       <outline title="Magyar Nemzet Online - H’rek" text="" xmlUrl="'. $path .'feed_without_guid.rss2" type="rss" />
       <outline title="Drupal planet" text="" type="rss" xmlUrl="'. $path .'drupalplanet.rss2" />
    </outline>
</body>
</opml>';
  print $output;
}